[project]
name = "synthetic-hls"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llm>=0.27.1",
    "llm-openrouter>=0.4.1",
    "matplotlib>=3.10.8",
    "psutil>=7.0.0",
    "python-dotenv>=1.2.1",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "joblib>=1.4.2",
    "hlsfactory @ git+https://github.com/sharc-lab/HLSFactory.git@mzhou_OptDSLv2",
    "networkx>=3.0",
    "scikit-learn>=1.4",
    "scipy>=1.12",
    "seaborn>=0.13",
    "tqdm>=4.66",
    "torch>=2.3",
    "torch-geometric>=2.5",
    "pytorch-warmup>=0.1.1",
]

[tool.setuptools]
packages = { find = { include = ["synthetic_hls*"] } }

# Include templates inside synthetic_hls
[tool.setuptools.package-data]
synthetic_hls = ["tcl_templates/*.tcl"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"